use_frameworks!
platform:ios,'10.0'
target 'IPaStoryboardSegues_Example' do
  pod 'IPaStoryboardSegues', :path => '../'

  target 'IPaStoryboardSegues_Tests' do
    inherit! :search_paths

    
  end
end
